add API functionality and GitHub Action Docker Support
Google-DevFest-North-America/openvp pull request #28
Opened 2023-02-05 17:13 UTC by vhorvath2010

2023-02-08 03:51 UTC, Sanjay-B requested changes
Overall looks good. Left some feedback.

2023-02-08 03:51 UTC, Sanjay-B commented on package.json
> +    "uuid": "^9.0.0"
Instead of importing an entire package just for uuid, you can do the following that included in native node: 
```nodejs
const crypto = require('crypto');
crypto.randomUUID(); // Generates random uuid i.e 00b6fg73-sd78-9734-8789-637263792878
```

2023-02-08 03:51 UTC, Sanjay-B commented on src/pages/api/signUpAPI.js
> +import { v4 as uuidv4 } from 'uuid';
Use native crypto module. It's the same stuff but, native.

2023-02-08 03:51 UTC, Sanjay-B commented on src/pages/api/signUpAPI.js
> +    /*
If we don't need comments, please remove it.

2023-02-08 03:51 UTC, Sanjay-B commented on src/pages/signup.js
> +    const configData = {
Why are we passing ``configData`` every time submit is clicked?

2023-02-08 03:51 UTC, Sanjay-B commented on src/pages/api/signUpAPI.js
> +    const app = initializeApp(firebaseConfig);
Why are we initializing the app every time the the method is invoked? What's being passed in through config will always be constant & passed as environmental variables, and packaged into the resulting docker image that would run on GCR.

2023-02-08 03:52 UTC, Sanjay-B commented
Nitpick: It might be worth it to include a description in your PR as to what this PR does. @vhorvath2010

2023-02-08 05:45 UTC, teamrocket77 requested changes
Just some questions

2023-02-08 05:45 UTC, teamrocket77 commented on src/pages/signup.js
> +            signUpUser(firebaseConfig, first, last, phone, email, university, social, resume, consent);
Just asking , is this correct usage of the api? I've seen this call an api and just get handled in some form thought nextjs, with the handler method,

2023-02-08 05:45 UTC, teamrocket77 commented on src/pages/signup.js
> +        apiKey: process.env.REACT_FIREBASE_API_KEY ? process.env.REACT_FIREBASE_API_KEY : null,
This is really the only portion that really leave me with some weird feelings, if the app doesn't build with the key because it's not supposed to be null I don't think we should override that functionality, unless we are just looking for building only. I know the Summit is around the corner we may be able to get a test for functionality, going before then to test that, just have to learn how to intercept api calls, in nextjs, Do you have any thought, feelings or reservations on using Cypress here @Sanjay-B @vhorvath2010

2023-02-08 06:00 UTC, Sanjay-B commented on src/pages/signup.js
> +        apiKey: process.env.REACT_FIREBASE_API_KEY ? process.env.REACT_FIREBASE_API_KEY : null,
I think Cypress might be one of those things where you might have to test it on a branch before I can fully commit to it. Partially because, I have no idea how it works & secondly, we'd be polluting the repo for minor changes. Is there a specific reason / heavy-weighted use case that would warrant that approach? @teamrocket77

2023-02-09 13:37 UTC, teamrocket77 commented on src/pages/signup.js
> +        apiKey: process.env.REACT_FIREBASE_API_KEY ? process.env.REACT_FIREBASE_API_KEY : null,
It is heavy, true. We could use a smaller solution but it was really just for ensuring that this works and will work with minor changes, since we have it in the other repo I thought some of the tests would be easy to manage, as opposed to learning a new testing solution. Mocha could also work ( which it pulls features from) @Sanjay-B

2023-02-09 13:47 UTC, teamrocket77 requested changes

2023-02-09 13:47 UTC, teamrocket77 commented on src/lib/api/signupFunction.js
> +            resume: 0
Are we removing the resume upload functionality or will this be added back in the future? @Sanjay-B @vhorvath2010

2023-02-09 13:47 UTC, teamrocket77 commented on next.config.js
> +  webpack: (config, { buildId, dev, defaultLoaders, nextRuntime, webpack }) => {
What's the purpose of this explicit web pack configuration nextjs [is already compatible](https://nextjs.org/docs/messages/webpack5), nextjs doesn't handle this in the background?
@Sanjay-B

2023-02-09 13:47 UTC, teamrocket77 commented on src/pages/api/signup.js
> +            const status = await signUpUser(body.first, body.last, body.phone, body.email, body.college, body.social, body.consent, body.resume);
@Sanjay-B maybe some next config options for input validation? it's easy and doesn't take a long like [this](https://github.com/KSU-Google-DSC/Webapp/blob/dev/src/next.config.js)

2023-02-10 20:50 UTC, Sanjay-B commented on package.json
> +    "uuid": "^9.0.0"
Resolved.

2023-02-10 20:51 UTC, Sanjay-B commented on src/pages/api/signUpAPI.js
> +import { v4 as uuidv4 } from 'uuid';
Resolved.

2023-02-10 20:51 UTC, Sanjay-B commented on src/pages/signup.js
> +    const configData = {
Resolved.

2023-02-10 20:51 UTC, Sanjay-B commented on src/pages/api/signUpAPI.js
> +    /*
Resolved.

2023-02-10 20:51 UTC, Sanjay-B commented on src/pages/api/signUpAPI.js
> +    const app = initializeApp(firebaseConfig);
Resolved.

2023-02-10 20:52 UTC, Sanjay-B commented on src/pages/signup.js
> +            signUpUser(firebaseConfig, first, last, phone, email, university, social, resume, consent);
Corrected as of  https://github.com/KSU-Google-DSC/Google-Summit-Solution/pull/28/commits/c14d42a71e04ccdb9e1b378b146dd1f0132a24f8. @teamrocket77

2023-02-10 20:54 UTC, Sanjay-B commented on src/pages/signup.js
> +        apiKey: process.env.REACT_FIREBASE_API_KEY ? process.env.REACT_FIREBASE_API_KEY : null,
I think that's valid. We do have to test this stuff eventually. If you want to test it, feel free to open up a branch and experiment. Let's test (no pun intended) this out and see where that takes us. @teamrocket77

2023-02-10 20:55 UTC, Sanjay-B commented on src/lib/api/signupFunction.js
> +            resume: 0
Added in the future. We ran into some issues with it. @vhorvath2010 is working to fix it.

2023-02-10 20:59 UTC, Sanjay-B commented on next.config.js
> +  webpack: (config, { buildId, dev, defaultLoaders, nextRuntime, webpack }) => {
So funny story, Webpack5 is not compatible with React which isn't compatible with Nextjs 13 out of the box. There's certain contexts (client & server) that are enforced per component. Since this change is new, all of the Google NPM packages haven't updated. So, you literally have to explicitly tell Webpack 5 not to break. If you didn't have this, you'd get these client-sided errors that are trying to call packages that don't actually exist (on client side) and only exist on serverside. I had to go through a ton of documentation to figure all that out and it was the most painful thing. Don't remove this because, the repo will literal explode. Surprised that they'd release a feature that was *that* breaking w / o given proper time but, I should've expected this. It's good ole' package hell for ya. 🙄 @teamrocket77

2023-02-10 21:01 UTC, Sanjay-B commented on src/pages/api/signup.js
> +            const status = await signUpUser(body.first, body.last, body.phone, body.email, body.college, body.social, body.consent, body.resume);
Add this as a feature. For now, we're aiming for minimum viable product. It's not explicitly needed but, if you want to write a PR to add it in, feel free. Not an immediate need. Good catch though. @teamrocket77

2023-02-10 21:02 UTC, Sanjay-B commented on package.json
> +    "turbo_dev": "next dev --turbo",
This will break if you run it. It's for a future Nextjs version that's going to release soon. Turbo is in alpha but, it's really nice for testing (when it works).

2023-02-10 21:04 UTC, Sanjay-B commented on src/lib/api/signupFunction.js
> +    // TODO: Real Logging
At some point, we need to figure out our logging situation. Logging things straight to console, even if it was piped, is bad design. We don't want to flood console like that.

2023-02-10 21:04 UTC, Sanjay-B commented on src/pages/_app.js
> +// import { SessionProvider } from "next-auth/react";
This is for a future version where we're going to control login. That's a next feature that we'll add in later down the road.

2023-02-10 21:06 UTC, Sanjay-B approved these changes
LGTM.

2023-02-12 15:50 UTC, teamrocket77 approved these changes
LGTM, thanks for answering questions and providing additional information

2023-02-14 18:02 UTC, Sanjay-B approved these changes
LGTM.

2023-02-14 18:02 UTC, merged